/// Flutter icons TaskBudIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TaskBudIcon
///      fonts:
///       - asset: fonts/TaskBudIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TaskBudIcon {
  TaskBudIcon._();

  static const _kFontFam = 'TaskBudIcon';
  static const _kFontPkg = null;

  static const IconData password = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at_circle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_portrait_sharp = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_sharp = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_open = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
